linters:
  disable:
    - maligned
    - scopelint
    - varcheck
    - ifshort
    - golint
    - interfacer
    - deadcode
    - nosnakecase
    - exhaustivestruct
    - rowserrcheck
    - sqlclosecheck
    - wastedassign
    - structcheck

    - tagliatelle

  enable-all: true