linters:
  disable:
    - maligned
    - scopelint
    - varcheck
    - ifshort
    - golint
    - interfacer
    - deadcode
    - nosnakecase
    - exhaustivestruct
    - rowserrcheck
    - sqlclosecheck
    - wastedassign
    - structcheck

    - tagliatelle
    - exhaustruct
    - godox

  enable-all: true