# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go mod tidy
builds:
  - binary: pap
    goos:
      - darwin
      - windows
      - linux
      - freebsd
      - solaris
      - plan9
      - openbsd
      - netbsd
      - illumos
      - dragonfly
      - android
      - aix
    goarch:
      - amd64
      - arm64
      - arm
      - "386"
      - ppc64le
      - ppc64
      - riscv64
      - s390x
      - loong64
      - mips
      - mips64
      - mipsle
      - mips64le
      - riscv64
    goarm:
      - "6"
      - "7"
    env:
      - CGO_ENABLED=0

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
