name: plugintest

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  unit-testing:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - uses: actions/checkout@v3

      - name: "Build pap"
        run: "go build ."
      
      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            +plugins/*.json

      - name: "Test changed packages"
        run: ./pap -y plugin install ${{ env.GIT_DIFF_FILTERED }}