name: plugintest

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  plugintest:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Get diff"
        shell: bash
        run: echo "CHANGES=$(./scripts/test_plugins.sh)" >> $GITHUB_ENV

      - uses: actions/setup-go@v3
        if: ${{ env.CHANGES != 'nochanges' }}
        with:
          go-version: '1.20'

      - name: "Build pap"
        if: ${{ env.CHANGES != 'nochanges' }}
        run: |
          make
          make install PREFIX=./

      - name: "Test changed plugins: ${{ env.CHANGES }}"
        if: ${{ env.CHANGES != 'nochanges' }}
        run: |
          echo $CHANGES
          ./bin/pap -y -d plugin install $CHANGES