name: plugintest

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  unit-testing:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Build pap"
        run: "go build ."
      
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35  
        with:
          files: |
            plugins/**

      - name: "Test changed packages"
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          "echo ${{ steps.changed-files-specific.outputs.all_changed_files }}"
          "./pap -y plugin install ${{ steps.changed-files-specific.outputs.all_changed_files }}"