name: plugintestall

on:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  plugintestall:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Build pap"
        run: |
          make
          make install PREFIX=./

      - name: "Test all plugins (unix)"
        if: matrix.os != 'windows-latest'
        run: "./bin/pap -y -d plugin install $(find plugins/*.json)"
      
      - name: "Test all plugins (windows)"
        if: matrix.os == 'windows-latest'
        run: "./bin/pap -y -d plugin install $((Get-ChildItem plugins/*.json).FullName)"