name: plugintest

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  plugintest:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Get diff"
        shell: bash
        id: "getdiff"
        run: "echo changes=$(./scripts/test_plugins.sh) >> $GITHUB_OUTPUT"

      - uses: actions/setup-go@v3
        if: (steps.getdiff.outputs.changes != 'nochanges')
        with:
          go-version: '1.20'

      - name: "Build pap"
        if: (steps.getdiff.outputs.changes != 'nochanges')
        run: "go build ."

      - name: "Test changed packages"
        if: (steps.getdiff.outputs.changes != 'nochanges')
        run: |
          echo ${{ steps.getdiff.outputs.changes }}
          ./pap -y plugin install ${{ steps.checksecrets.outputs.changes }}