name: testing
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  testing:
    strategy:
      matrix:
        go: [1.18, 1.19]
        os: [macos-latest, windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - uses: actions/checkout@v3

      - run: "go build ."
      - run: "./pap help"
      - run: "./pap download"
      - run: "./pap download --version 1.19.2"
      - run: "./pap download --version 1.19.2 --build 300"
      - run: "./pap download --version 1.12.2 --build 1230"
      - run: "./pap download --version 1.12.2"
      - run: "./pap download --version latest --build latest"
      - run: "./pap download --version 1.12.2 --build latest"
      - run: "./pap sign"
      - run: "./pap script"
      - run: "./pap script -xmx 2G"
      - run: "./pap script -xms 2G"
      - run: "./pap script -xms 2G -gui"
      - run: "./pap script -jar wow.jar"
      - run: "./pap script -jar wow.jar -gui"
      - run: "./pap script -jar -gui wow.jar"
      - run: "./pap script -jar wow.jar -xms 1G -xmx 4G -gui"
      - run: "./pap version"
